# Generated by Django 2.0.5 on 2018-07-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': True,
                'db_table': 'topic_agent',
            },
        ),
        migrations.RemoveField(
            model_name='agents',
            name='topic',
        ),
        migrations.AddField(
            model_name='topicagent',
            name='agentid',
            field=models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='user.Agents'),
        ),
        migrations.AddField(
            model_name='topicagent',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.CASCADE, to='user.Topics'),
        ),
    ]
