# Generated by Django 2.0.5 on 2018-07-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='token',
            new_name='key',
        ),
    ]
