# Generated by Django 2.0.5 on 2018-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_users_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
